PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS SEARCH_URLS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  canonical_url TEXT NOT NULL UNIQUE,
  original_url TEXT NOT NULL,
  image_url TEXT,
  provider TEXT,
  source TEXT,
  first_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_SEARCH_URLS_SOURCE ON SEARCH_URLS(source, last_seen_at DESC);
CREATE INDEX IF NOT EXISTS IDX_SEARCH_RESULTS_CANONICAL_URL ON SEARCH_RESULTS(canonical_url);
