PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS SEARCH_CRAWL_JOBS (
  id TEXT PRIMARY KEY,
  crawl_key TEXT NOT NULL UNIQUE,
  provider TEXT NOT NULL,
  query TEXT NOT NULL,
  params_json TEXT NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'queued',
  next_bookmark TEXT,
  pages_completed INTEGER NOT NULL DEFAULT 0,
  results_count INTEGER NOT NULL DEFAULT 0,
  attempts INTEGER NOT NULL DEFAULT 0,
  error_message TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TEXT
);

CREATE INDEX IF NOT EXISTS IDX_SEARCH_CRAWL_JOBS_STATUS
  ON SEARCH_CRAWL_JOBS(status, updated_at);

CREATE TABLE IF NOT EXISTS SEARCH_CRAWL_ITEMS (
  crawl_id TEXT NOT NULL REFERENCES SEARCH_CRAWL_JOBS(id) ON DELETE CASCADE,
  canonical_url TEXT NOT NULL REFERENCES SEARCH_RESULTS(canonical_url) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(crawl_id, canonical_url)
);

CREATE INDEX IF NOT EXISTS IDX_SEARCH_CRAWL_ITEMS_CRAWL
  ON SEARCH_CRAWL_ITEMS(crawl_id, created_at);
